### ISSUE TITLE
Only one policy file changed when multiple exist

### ISSUE THREAD

**Issue by Eridyne** [Magisk-Modules-Alt-Repo/drc-remover#1]
Device: OnePlus 9 Pro
OS: Android 13 (crDroid v9) with Magisk 25.2
Version: drc-remover 1.0, Magisk module

Expected result: 
There are three audio_policy_configuration*.xml files under /vendor/etc/, in different subdirectories, all with speaker_drc_enabled="true". The readme is unclear, but implies that all three should be copied to the drc-remover module directory, modified, and overlaid on the originals.

Actual result: 
Only one file is copied and modified. The other two files are not copied and still have speaker_drc_enabled="true".

Notes:
If the module is intended to intelligently retrieve the current active audio policy file, and only patch that, I would suggest adding that to the readme. Not a coder, so I haven't examined the module to try to see how it works.

**Comment by yzyhk904** [comment]
Sorry for a late reply. I don't know the reason, but this hasn't been notified to me by e-mail.

There may be several main configuration files, e.g. audio_policy_configuration.xml, audio_policy_configuration_a2dp_offload_disabled.xml, audio_policy_bluetooth_legacy_hal.xml, etc. However there is only one main configuration file to be active. The active one can be changed by some switches in special settings menus. This module  detects the current active one automatically. So if you changed the active one to another, this module couldn't disable DRC any more. Of course, you can disable DRC by re-installing this module.

The problem is how to know all the main configuration files and where they are exactly. I don't know the automatic way.

I'll add some explanation to the readme.
